# 自动生成的模型配置文件
# 生成时间: 2025-08-06 13:05:15
# 用户: benderick
# 模板: yolo11-Conv-CSP_StripModule-None-Concat-AFPNHead
# 模型名称: yolo11-Conv-CSP_StripModule-None-Concat-AFPNHead
# 
# 配置参数:
#   - 下采样模块: Conv
#   - 卷积模块: CSP_StripModule  
#   - 融合模块: Concat
#   - 检测头: AFPNHead
name: yolo11-Conv-CSP_StripModule-None-Concat-AFPNHead
nc: 80
scales:
  # [depth, width, max_channels]
  n: [0.5, 0.25, 1024]
  s: [0.5, 0.5, 1024]
  m: [0.5, 1.0, 512]
  l: [1.0, 1.0, 512]
  x: [1.0, 1.5, 512]
DOWNSAMPLE: Conv
CONVOLUTION: CSP_StripModule
ATTENTION: null
FUSION: Concat
HEAD: AFPNHead
UPSAMPLE: nn.Upsample

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 2, CSP_StripModule, [256, false, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 2, CSP_StripModule, [512, false, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 2, CSP_StripModule, [512, true]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 2, CSP_StripModule, [1024, true]]
  - [-1, 1, SPPF, [1024, 5]]
  - [-1, 2, C2PSA, [1024]]

head:
  - [-1, 1, nn.Upsample, [None, 2, nearest]]
  - [[-1, 6], 1, Concat, [1]]
  - [-1, 2, CSP_StripModule, [512, false]]
  - [-1, 1, nn.Upsample, [None, 2, nearest]]
  - [[-1, 4], 1, Concat, [1]]
  - [-1, 2, CSP_StripModule, [256, false]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]]
  - [-1, 2, CSP_StripModule, [512, false]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]]
  - [-1, 2, CSP_StripModule, [1024, true]]
  - [[16, 19, 22], 1, AFPNHead, [nc]]
